server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
            https://github.com/Vishwasp13/KafkaConsumer